//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.RocketMatter.Authentication {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseObject", Namespace="http://schemas.datacontract.org/2004/07/Origin.Core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.BaseValidationObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.BaseDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.BaseRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.RefreshTokenRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.RevokeTokenRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GetMobileAuthenticationCodeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GrantTokenRequest))]
    public partial class BaseObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ExternalIDk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ExternalID>k__BackingField", IsRequired=true)]
        public string ExternalIDk__BackingField {
            get {
                return this.ExternalIDk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIDk__BackingFieldField, value) != true)) {
                    this.ExternalIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("ExternalIDk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseValidationObject", Namespace="http://schemas.datacontract.org/2004/07/Origin.Core.Validation.Classes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.BaseDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.BaseRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.RefreshTokenRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.RevokeTokenRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GetMobileAuthenticationCodeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GrantTokenRequest))]
    public partial class BaseValidationObject : MC.RocketMatter.Authentication.BaseObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDTO", Namespace="http://schemas.datacontract.org/2004/07/Otive.Web.API_V2.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.BaseRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.RefreshTokenRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.RevokeTokenRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GetMobileAuthenticationCodeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GrantTokenRequest))]
    public partial class BaseDTO : MC.RocketMatter.Authentication.BaseValidationObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/Otive.Web.API_V2.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.RefreshTokenRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.RevokeTokenRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GetMobileAuthenticationCodeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GrantTokenRequest))]
    public partial class BaseRequest : MC.RocketMatter.Authentication.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FailPendingPaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTestingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool @__ForceCacheResetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FailPendingPayments {
            get {
                return this.FailPendingPaymentsField;
            }
            set {
                if ((this.FailPendingPaymentsField.Equals(value) != true)) {
                    this.FailPendingPaymentsField = value;
                    this.RaisePropertyChanged("FailPendingPayments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTesting {
            get {
                return this.IsTestingField;
            }
            set {
                if ((this.IsTestingField.Equals(value) != true)) {
                    this.IsTestingField = value;
                    this.RaisePropertyChanged("IsTesting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceCode {
            get {
                return this.ServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCodeField, value) != true)) {
                    this.ServiceCodeField = value;
                    this.RaisePropertyChanged("ServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool @__ForceCacheReset {
            get {
                return this.@__ForceCacheResetField;
            }
            set {
                if ((this.@__ForceCacheResetField.Equals(value) != true)) {
                    this.@__ForceCacheResetField = value;
                    this.RaisePropertyChanged("__ForceCacheReset");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefreshTokenRequest", Namespace="http://schemas.datacontract.org/2004/07/Otive.Web.API_V2.DTO.Request.Authenticati" +
        "on")]
    [System.SerializableAttribute()]
    public partial class RefreshTokenRequest : MC.RocketMatter.Authentication.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string refresh_tokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string refresh_token {
            get {
                return this.refresh_tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.refresh_tokenField, value) != true)) {
                    this.refresh_tokenField = value;
                    this.RaisePropertyChanged("refresh_token");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RevokeTokenRequest", Namespace="http://schemas.datacontract.org/2004/07/Otive.Web.API_V2.DTO.Request.Authenticati" +
        "on")]
    [System.SerializableAttribute()]
    public partial class RevokeTokenRequest : MC.RocketMatter.Authentication.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMobileAuthenticationCodeRequest", Namespace="http://schemas.datacontract.org/2004/07/Otive.Web.API_V2.DTO.Request.Mobile")]
    [System.SerializableAttribute()]
    public partial class GetMobileAuthenticationCodeRequest : MC.RocketMatter.Authentication.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticationTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationToken {
            get {
                return this.AuthenticationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenField, value) != true)) {
                    this.AuthenticationTokenField = value;
                    this.RaisePropertyChanged("AuthenticationToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrantTokenRequest", Namespace="http://schemas.datacontract.org/2004/07/Otive.Web.API_V2.DTO.Request.Authenticati" +
        "on")]
    [System.SerializableAttribute()]
    public partial class GrantTokenRequest : MC.RocketMatter.Authentication.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string client_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string client_secretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string grant_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string client_id {
            get {
                return this.client_idField;
            }
            set {
                if ((object.ReferenceEquals(this.client_idField, value) != true)) {
                    this.client_idField = value;
                    this.RaisePropertyChanged("client_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string client_secret {
            get {
                return this.client_secretField;
            }
            set {
                if ((object.ReferenceEquals(this.client_secretField, value) != true)) {
                    this.client_secretField = value;
                    this.RaisePropertyChanged("client_secret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string grant_type {
            get {
                return this.grant_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.grant_typeField, value) != true)) {
                    this.grant_typeField = value;
                    this.RaisePropertyChanged("grant_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/Otive.Web.API_V2.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.RevokeTokenResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GetMobileAuthenticationCodeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GrantTokenResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CachedResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MC.RocketMatter.Authentication.ValidationResult[] FailedValidationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDirtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CachedResult {
            get {
                return this.CachedResultField;
            }
            set {
                if ((this.CachedResultField.Equals(value) != true)) {
                    this.CachedResultField = value;
                    this.RaisePropertyChanged("CachedResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorNumber {
            get {
                return this.ErrorNumberField;
            }
            set {
                if ((this.ErrorNumberField.Equals(value) != true)) {
                    this.ErrorNumberField = value;
                    this.RaisePropertyChanged("ErrorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MC.RocketMatter.Authentication.ValidationResult[] FailedValidations {
            get {
                return this.FailedValidationsField;
            }
            set {
                if ((object.ReferenceEquals(this.FailedValidationsField, value) != true)) {
                    this.FailedValidationsField = value;
                    this.RaisePropertyChanged("FailedValidations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDirty {
            get {
                return this.IsDirtyField;
            }
            set {
                if ((this.IsDirtyField.Equals(value) != true)) {
                    this.IsDirtyField = value;
                    this.RaisePropertyChanged("IsDirty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RevokeTokenResponse", Namespace="http://schemas.datacontract.org/2004/07/Otive.Web.API_V2.DTO.Response.Authenticat" +
        "ion")]
    [System.SerializableAttribute()]
    public partial class RevokeTokenResponse : MC.RocketMatter.Authentication.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMobileAuthenticationCodeResponse", Namespace="http://schemas.datacontract.org/2004/07/Otive.Web.API_V2.DTO.Response.Mobile")]
    [System.SerializableAttribute()]
    public partial class GetMobileAuthenticationCodeResponse : MC.RocketMatter.Authentication.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsValidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationCode {
            get {
                return this.AuthenticationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationCodeField, value) != true)) {
                    this.AuthenticationCodeField = value;
                    this.RaisePropertyChanged("AuthenticationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrantTokenResponse", Namespace="http://schemas.datacontract.org/2004/07/Otive.Web.API_V2.DTO.Response.Authenticat" +
        "ion")]
    [System.SerializableAttribute()]
    public partial class GrantTokenResponse : MC.RocketMatter.Authentication.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string access_tokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime expires_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> expires_inField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string refresh_tokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string access_token {
            get {
                return this.access_tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.access_tokenField, value) != true)) {
                    this.access_tokenField = value;
                    this.RaisePropertyChanged("access_token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime expires_at {
            get {
                return this.expires_atField;
            }
            set {
                if ((this.expires_atField.Equals(value) != true)) {
                    this.expires_atField = value;
                    this.RaisePropertyChanged("expires_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> expires_in {
            get {
                return this.expires_inField;
            }
            set {
                if ((this.expires_inField.Equals(value) != true)) {
                    this.expires_inField = value;
                    this.RaisePropertyChanged("expires_in");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string refresh_token {
            get {
                return this.refresh_tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.refresh_tokenField, value) != true)) {
                    this.refresh_tokenField = value;
                    this.RaisePropertyChanged("refresh_token");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResult", Namespace="http://schemas.datacontract.org/2004/07/Origin.Core.Validation.Classes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.BaseRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.BaseDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.BaseResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GrantTokenRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.RefreshTokenRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.RevokeTokenRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.BaseObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GetMobileAuthenticationCodeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GrantTokenResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.RevokeTokenResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.GetMobileAuthenticationCodeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.BaseValidationObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MC.RocketMatter.Authentication.ValidationResult[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class ValidationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] FailedValidationMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MaxLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MaxValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MinLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MinValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrecisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyDisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueEnteredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalID {
            get {
                return this.ExternalIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIDField, value) != true)) {
                    this.ExternalIDField = value;
                    this.RaisePropertyChanged("ExternalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] FailedValidationMessages {
            get {
                return this.FailedValidationMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.FailedValidationMessagesField, value) != true)) {
                    this.FailedValidationMessagesField = value;
                    this.RaisePropertyChanged("FailedValidationMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MaxLength {
            get {
                return this.MaxLengthField;
            }
            set {
                if ((this.MaxLengthField.Equals(value) != true)) {
                    this.MaxLengthField = value;
                    this.RaisePropertyChanged("MaxLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MaxValue {
            get {
                return this.MaxValueField;
            }
            set {
                if ((this.MaxValueField.Equals(value) != true)) {
                    this.MaxValueField = value;
                    this.RaisePropertyChanged("MaxValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MinLength {
            get {
                return this.MinLengthField;
            }
            set {
                if ((this.MinLengthField.Equals(value) != true)) {
                    this.MinLengthField = value;
                    this.RaisePropertyChanged("MinLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MinValue {
            get {
                return this.MinValueField;
            }
            set {
                if ((this.MinValueField.Equals(value) != true)) {
                    this.MinValueField = value;
                    this.RaisePropertyChanged("MinValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectName {
            get {
                return this.ObjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectNameField, value) != true)) {
                    this.ObjectNameField = value;
                    this.RaisePropertyChanged("ObjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Precision {
            get {
                return this.PrecisionField;
            }
            set {
                if ((this.PrecisionField.Equals(value) != true)) {
                    this.PrecisionField = value;
                    this.RaisePropertyChanged("Precision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyDisplayName {
            get {
                return this.PropertyDisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyDisplayNameField, value) != true)) {
                    this.PropertyDisplayNameField = value;
                    this.RaisePropertyChanged("PropertyDisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Required {
            get {
                return this.RequiredField;
            }
            set {
                if ((this.RequiredField.Equals(value) != true)) {
                    this.RequiredField = value;
                    this.RaisePropertyChanged("Required");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ValueEntered {
            get {
                return this.ValueEnteredField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueEnteredField, value) != true)) {
                    this.ValueEnteredField = value;
                    this.RaisePropertyChanged("ValueEntered");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Authentication.IAuthentication")]
    public interface IAuthentication {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/GrantToken", ReplyAction="http://tempuri.org/IAuthentication/GrantTokenResponse")]
        MC.RocketMatter.Authentication.GrantTokenResponse GrantToken(MC.RocketMatter.Authentication.GrantTokenRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/GrantToken", ReplyAction="http://tempuri.org/IAuthentication/GrantTokenResponse")]
        System.Threading.Tasks.Task<MC.RocketMatter.Authentication.GrantTokenResponse> GrantTokenAsync(MC.RocketMatter.Authentication.GrantTokenRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/RefreshToken", ReplyAction="http://tempuri.org/IAuthentication/RefreshTokenResponse")]
        MC.RocketMatter.Authentication.GrantTokenResponse RefreshToken(MC.RocketMatter.Authentication.RefreshTokenRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/RefreshToken", ReplyAction="http://tempuri.org/IAuthentication/RefreshTokenResponse")]
        System.Threading.Tasks.Task<MC.RocketMatter.Authentication.GrantTokenResponse> RefreshTokenAsync(MC.RocketMatter.Authentication.RefreshTokenRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/LogOut", ReplyAction="http://tempuri.org/IAuthentication/LogOutResponse")]
        MC.RocketMatter.Authentication.BaseResponse LogOut(MC.RocketMatter.Authentication.BaseRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/LogOut", ReplyAction="http://tempuri.org/IAuthentication/LogOutResponse")]
        System.Threading.Tasks.Task<MC.RocketMatter.Authentication.BaseResponse> LogOutAsync(MC.RocketMatter.Authentication.BaseRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/GetNewRefreshToken", ReplyAction="http://tempuri.org/IAuthentication/GetNewRefreshTokenResponse")]
        MC.RocketMatter.Authentication.GrantTokenResponse GetNewRefreshToken(MC.RocketMatter.Authentication.GrantTokenRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/GetNewRefreshToken", ReplyAction="http://tempuri.org/IAuthentication/GetNewRefreshTokenResponse")]
        System.Threading.Tasks.Task<MC.RocketMatter.Authentication.GrantTokenResponse> GetNewRefreshTokenAsync(MC.RocketMatter.Authentication.GrantTokenRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/RevokeToken", ReplyAction="http://tempuri.org/IAuthentication/RevokeTokenResponse")]
        MC.RocketMatter.Authentication.RevokeTokenResponse RevokeToken(MC.RocketMatter.Authentication.RevokeTokenRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/RevokeToken", ReplyAction="http://tempuri.org/IAuthentication/RevokeTokenResponse")]
        System.Threading.Tasks.Task<MC.RocketMatter.Authentication.RevokeTokenResponse> RevokeTokenAsync(MC.RocketMatter.Authentication.RevokeTokenRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/GetMobileAuthenticationCode", ReplyAction="http://tempuri.org/IAuthentication/GetMobileAuthenticationCodeResponse")]
        MC.RocketMatter.Authentication.GetMobileAuthenticationCodeResponse GetMobileAuthenticationCode(MC.RocketMatter.Authentication.GetMobileAuthenticationCodeRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/GetMobileAuthenticationCode", ReplyAction="http://tempuri.org/IAuthentication/GetMobileAuthenticationCodeResponse")]
        System.Threading.Tasks.Task<MC.RocketMatter.Authentication.GetMobileAuthenticationCodeResponse> GetMobileAuthenticationCodeAsync(MC.RocketMatter.Authentication.GetMobileAuthenticationCodeRequest req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationChannel : MC.RocketMatter.Authentication.IAuthentication, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationClient : System.ServiceModel.ClientBase<MC.RocketMatter.Authentication.IAuthentication>, MC.RocketMatter.Authentication.IAuthentication {
        
        public AuthenticationClient() {
        }
        
        public AuthenticationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MC.RocketMatter.Authentication.GrantTokenResponse GrantToken(MC.RocketMatter.Authentication.GrantTokenRequest req) {
            return base.Channel.GrantToken(req);
        }
        
        public System.Threading.Tasks.Task<MC.RocketMatter.Authentication.GrantTokenResponse> GrantTokenAsync(MC.RocketMatter.Authentication.GrantTokenRequest req) {
            return base.Channel.GrantTokenAsync(req);
        }
        
        public MC.RocketMatter.Authentication.GrantTokenResponse RefreshToken(MC.RocketMatter.Authentication.RefreshTokenRequest req) {
            return base.Channel.RefreshToken(req);
        }
        
        public System.Threading.Tasks.Task<MC.RocketMatter.Authentication.GrantTokenResponse> RefreshTokenAsync(MC.RocketMatter.Authentication.RefreshTokenRequest req) {
            return base.Channel.RefreshTokenAsync(req);
        }
        
        public MC.RocketMatter.Authentication.BaseResponse LogOut(MC.RocketMatter.Authentication.BaseRequest req) {
            return base.Channel.LogOut(req);
        }
        
        public System.Threading.Tasks.Task<MC.RocketMatter.Authentication.BaseResponse> LogOutAsync(MC.RocketMatter.Authentication.BaseRequest req) {
            return base.Channel.LogOutAsync(req);
        }
        
        public MC.RocketMatter.Authentication.GrantTokenResponse GetNewRefreshToken(MC.RocketMatter.Authentication.GrantTokenRequest req) {
            return base.Channel.GetNewRefreshToken(req);
        }
        
        public System.Threading.Tasks.Task<MC.RocketMatter.Authentication.GrantTokenResponse> GetNewRefreshTokenAsync(MC.RocketMatter.Authentication.GrantTokenRequest req) {
            return base.Channel.GetNewRefreshTokenAsync(req);
        }
        
        public MC.RocketMatter.Authentication.RevokeTokenResponse RevokeToken(MC.RocketMatter.Authentication.RevokeTokenRequest req) {
            return base.Channel.RevokeToken(req);
        }
        
        public System.Threading.Tasks.Task<MC.RocketMatter.Authentication.RevokeTokenResponse> RevokeTokenAsync(MC.RocketMatter.Authentication.RevokeTokenRequest req) {
            return base.Channel.RevokeTokenAsync(req);
        }
        
        public MC.RocketMatter.Authentication.GetMobileAuthenticationCodeResponse GetMobileAuthenticationCode(MC.RocketMatter.Authentication.GetMobileAuthenticationCodeRequest req) {
            return base.Channel.GetMobileAuthenticationCode(req);
        }
        
        public System.Threading.Tasks.Task<MC.RocketMatter.Authentication.GetMobileAuthenticationCodeResponse> GetMobileAuthenticationCodeAsync(MC.RocketMatter.Authentication.GetMobileAuthenticationCodeRequest req) {
            return base.Channel.GetMobileAuthenticationCodeAsync(req);
        }
    }
}
